### PR TITLE
update README and doc example to use async / await

### PR DESCRIPTION
**Pull request by andrewbanchich**
I updated the layout of the README, added a badge linking directly to the docs, changed the example to use async / await since it's stable now, and removed `lapin_futures` from the README since it sounds like that shouldn't be used anymore.

### CODE REVIEW

**Comment by Keruspe** [comment]
Looks nice! thanks!

**Comment by frederikbosch** [comment]
I think the example is not completely correct. You must call `into_iter()` on the consumer before you can use it. Furthermore, since `async move |param|` is unstable, you will have to use `.wait()` inside the `for_each`. Or am I not correct?

My working example looks as follows.

```rust
consumer
    .into_iter()
    .for_each(move |delivery| {
        let delivery = delivery.expect("Couldn't receive delivery from RabbitMQ.");
        println!("{:?}", delivery);

        channel
            .basic_ack(delivery.delivery_tag, BasicAckOptions::default())
            .wait()
            .unwrap();
    })
`

**Comment by andrewbanchich** [comment]
I tested the example out on stable and it worked.

**Comment by frederikbosch** [comment]
@andrewbanchich I believe I hit this one: https://github.com/rust-lang/rust/issues/62290.

**Comment by andrewbanchich** [comment]
Ah, I see. You are correct that async closures are unstable, but the README example doesn't use them: it has an async block directly above a normal `move |param| ...`

**Pull request merged**
