### PR TITLE
Fix issues with heartbeats stopping consumers

### LINKED ISSUE #125: Heartbeat blocks all consumers from continuing in 0.12
```
MeterSnapshot { count: 414665, rates: [390.8100698087718, 730.5750441311204, 963.6300314729459], mean: 813.0564690986009 }
name: message_count labels: None
MeterSnapshot { count: 420872, rates: [394.6336229561739, 715.0688686739221, 954.5356931002789], mean: 801.6491752048053 }
name: message_count labels: None
MeterSnapshot { count: 425793, rates: [379.84412870857903, 696.1875593463596, 944.1788324173962], mean: 788.4941713438777 }
name: message_count labels: None
MeterSnapshot { count: 431172, rates: [374.9080306879829, 679.7197843340775, 934.5018666347837], mean: 776.8754486373127 }
name: message_count labels: None
MeterSnapshot { count: 436343, rates: [368.5097618284864, 663.3929785381047, 924.7543420213268], mean: 765.5033310586701 }
DEBUG 2018-06-16T19:19:38Z: lapin_futures::client: poll heartbeat
DEBUG 2018-06-16T19:19:38Z: lapin_futures::client: Sending heartbeat
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [334.91339771824613, 642.0454100051794, 913.2244909211752], mean: 751.7178407188896 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [260.830816404075, 610.7324858625518, 898.1302177517547], mean: 732.9250308062573 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [203.13524406464748, 580.9467110509256, 883.285430973444], mean: 715.0489367894609 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [158.20188714694842, 552.6136056185545, 868.6860069389069], mean: 698.0240798297584 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [123.20775359341746, 525.6623220438021, 854.3278901587024], mean: 681.7910729352898 }
name: message_count labels: None
MeterSnapshot { count: 439761, rates: [95.95429497902224, 500.0254680794349, 840.2070921747342], mean: 666.2959256376611 }
```

These are my logs, showing 15 second windows of the rates. You can see that the moment the heartbeat sends, the count stops increasing and no messages are received. I confirmed this by looking in the RabbitMQ UI, and seeing a delivery rate of 0/s.

### PR DESCRIPTION
**Pull request by whitfin**
This appears to fix #125.

No idea why, but I tested it and could no longer reproduce my issue :)

### CODE REVIEW

**Comment by Keruspe** [comment]
I suspected it came from there too.
Could you explain how I can reproduce or do some further testing if I give you pointers to find the root cause?

**Comment by whitfin** [comment]
@Keruspe I didn't do anything specific; I have an app that listens for around 300 messages per second, and sometimes the heartbeat log shows up like this:

```
DEBUG 2018-06-23T18:09:49Z: lapin_futures::client: poll heartbeat
DEBUG 2018-06-23T18:09:49Z: lapin_futures::client: Sending heartbeat
```

And then the message rate just drops to 0; you could probably replicate with the consumers example if you can generate a larger amount of messages going through to them.

Feel free to give me some places to look and I can dig in further!

**Comment by Keruspe** [comment]
One first step would be to replace the poll() call with some Ok(Async::Ready(())) to see if the problem comes from the locking (unlikely) or the polling (I suspect so)

Then if it comes from the polling, trying to find which part of the poll() call is guilty by calling only subparts of poll()

**Comment by whitfin** [comment]
@Keruspe Replacing the poll call with just `Ok(Async::Ready(()))` also appears to fix the problem - some issue with locking? Is there a need to call poll here, or can we just skip that poll call?

**Comment by Keruspe** [comment]
The problem is not with the locking part but rather with the poll() call as expected.
We really need to keep this poll() call as it’s at least needed if there is no other activity than the consumer.
Now to figure out which part of the poll is guilty...

**Comment by Keruspe** [comment]
I made some changes that make the poll() call unnecessary, should be fixed in master, thanks for reporting and finding the exact culprit!

**Comment by whitfin** [comment]
@Keruspe awesome, I'll check it out. Side note; is there any chance this can be bumped in a patch release soon-ish? We were hoping on using this library for a project pretty soon but this is a killer for us (and I really don't want to point at master).

**Comment by Keruspe** [comment]
Yup, I just want to merge #127 and add a Changelog to fix #120 and we'll be good for a release I think. Hopefully this week

**Comment by Keruspe** [comment]
@whitfin I’m writing the changelog, release should arrive real soon, sorry for the delay

**Pull request closed without merging**
